"""
Name: Ayush Jain
Roll No. : FCB44
Class : COMP-B
"""
print("Name: Ayush Jain\nRoll No. : FCB44\nClass : COMP-B")
students = ["Ayush", "Atharv", "Daksh", "Shreyash", "Vedant", "Ashutosh"]
print(students)
students.append("Mangesh")
print(students)
students.insert(1, "Ash")
print(students)
students.pop()
print(students)
students.remove("Ash")
print(students)
students.sort()
print(students)
students.reverse()
print(students)
students.clear()
print(students)
l = [1, 2,3, 4, 5, 6]
l.append(5)
print(l)
l.insert(5, 8)
print(l)
l.remove(4)
print(l)
l.pop(6)
l.pop()
l.sort()
print(l)
l.reverse()
print(l)
l.index(3)
l.append(4, 5, 6, 4, 5,5)
l.append(4)
l.count(4)
l.clear()
print(l)
